version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: ims-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: computerengineering
      MYSQL_DATABASE: inventory_management_system_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/database/inventory_management_system_database.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: ims-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: computerengineering
      DB_NAME: inventory_management_system_database
    # If you want to run with a GUI, extra setup is needed (X11 forwarding, VNC, etc.)
    # For now, this runs the app headlessly (for server-side or CLI JavaFX usage)
    # If you want to run the GUI, see README for instructions
    # ports:
    #   - "8080:8080"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ims-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: computerengineering
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
